- name: install apache
  apt: pkg=apache2 state=latest
  become: yes

- name: disable default vhost
  file: name=/etc/apache2/sites-enabled/000-default state=absent
  become: yes
  when: ansible_lsb.major_release|int < 8
  notify: reload apache

- name: disable default vhost
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent
  become: yes
  when: ansible_lsb.major_release|int >= 8
  notify: reload apache

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  become: yes
  with_items:
      - rewrite
      - vhost_alias
      - mime
      - deflate
      - headers
  notify: restart apache

- name: enable Apache SSL module
  apache2_module: state=present name=ssl
  become: yes
  when: ssl
  notify: restart apache

- name: create vhost config
  template: src={{ site_template }} dest=/etc/apache2/sites-available/{{ hostname }}.conf
  become: yes

- name: enable vhost
  file: src=/etc/apache2/sites-available/{{ hostname }}.conf dest=/etc/apache2/sites-enabled/0001-{{ hostname }}.conf state=link
  become: yes
  notify: reload apache

- meta: flush_handlers
